In [1]:
import sys

In [ ]:
!{sys.executable} main.py --data_path "data/reviews.csv" --epochs 10

Figure(640x480)
/user_data/envs/LLMs/lib/python3.8/site-packages/transformers/optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Epoch 1/10
Evaluating: 100%|█████████████████████████████| 197/197 [00:10<00:00, 18.73it/s]
Train loss: 0.7478 accuracy: 0.6524
Validation loss: 0.6393 accuracy: 0.7390
Epoch 2/10
Evaluating: 100%|█████████████████████████████| 197/197 [00:10<00:00, 18.55it/s]
Train loss: 0.4949 accuracy: 0.8007
Validation loss: 0.5980 accuracy: 0.7905
Epoch 3/10
Evaluating: 100%|█████████████████████████████| 197/197 [00:10<00:00, 18.56it/s]
Train loss: 0.2997 accuracy: 0.8922
Validation loss: 0.6652 accuracy: 0.8229
Epoch 4/10
Evaluating: 100%|█████████████████████████████| 197/197 [00:10<00:00, 18.51it/s]
Train loss: 0.2013 accuracy: 0.9371
Validation loss: 0.7000 accurac

In [ ]:
!{sys.executable} inference.py --test_data_path 'data/test.csv' \
--model_path 'best_model_state.bin' \
--output_path 'infr_result.csv'

Inference results saved to infr_result.csv


In [4]:
!{sys.executable} eval.py --inference_results_path 'infr_result.csv'

Confusion Matrix:
[[ 856  112   29]
 [  68  838   73]
 [  27  115 1032]]
Figure(800x600)
Classification Report:
              precision    recall  f1-score   support

    negative       0.90      0.86      0.88       997
     neutral       0.79      0.86      0.82       979
    positive       0.91      0.88      0.89      1174

    accuracy                           0.87      3150
   macro avg       0.87      0.86      0.86      3150
weighted avg       0.87      0.87      0.87      3150

